#!/usr/bin/env bash
# As an answer file : bash script that configures a new Ubuntu machine to respect requirements:
# 1. Install nginx on your web-01 server, Nginx should be listening on port 80
# 2. When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Holberton School
# before checking: ./0-transfer_file 1-install_nginx_web_server 35.190.132.204 ubuntu ~/.ssh/holberton

# update my local package index so that I have access to the most recent package listings
apt-get -y update
apt-get -y install nginx

# the most restrictive profile because I havent configured SSL for my server, will allow traffic on port 80
#sudo ufw allow 'Nginx HTTP'

# NGinx Default public www location :
# https://stackoverflow.com/questions/10674867/nginx-default-public-www-location
echo "Holberton School" > /var/www/html/index.nginx-debian.html

# restarting nginx without systemctl
# sudo service restart nginx
service nginx start
