#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page. Requirements:
# - the redirection must be a 301 Moved Permanently
# - answer file : bash script containing commands to automatically configure a Ubuntu machine to respect requirements

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "s/listen 80 default_server;/listen 80 default_server;\n	rewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart
