#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page. Requirements:
# - the page must return an HTTP 404 error code
# - the page must contain the string: Ceci n'est pas une page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"

sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

sudo touch /var/www/html/custom_404.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo echo "<h1 style='color:red'>Error 404: Not found :-(</h1>" | sudo tee -a /var/www/html/custom_404.html

sudo sed -i "s/listen 80 default_server;/listen 80 default_server;\n	error_page 404 \/custom_404.html;\n	rewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart
