#!/usr/bin/env bash
#Script that pings an IP address passed as an arguments
#Accepts a string as an argument
#Displays Usage if no argument passed
#Ping the IP 5 times

if [[ $1 -eq 0 ]]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c5 "$1"
fi
