#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times , but for the 9th iteration, displays Holberton School and then Hi on a new line

x=0
while [ $x -le 10 ]
do
	if [ "$x" == 9 ]
	then
		echo "Hi"
	else
		echo "Holberton School"
	fi
x=$(( x + 1 ))
done
