#!/usr/bin/env bash
# Displays numbers from 1 to 20 with conditions

x=1
while [ $x -le 20 ]
do
	echo $x
	x=$(( x + 1 ))


case "$x" in

5) echo "bad luck from China"
	;;
10) echo "bad luck from Japan"
	;;
18) echo "bad luck from Italy"
	;;
esac
done
