#!/usr/bin/env bash
# Script that configures an Ubuntu server
# Requirements :
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8.
# - the checker is running on Docker, so make sure to read this
cp /etc/hosts ~/hosts.new
sed  -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
