#!/usr/bin/env bash
# To get Apache to run on the container and to return a page containing Hello Holberton when querying the root of it
# https://www.cyberciti.biz/faq/star-stop-restart-apache2-webserver/

sudo service apache2 start
