#!/usr/bin/env bash
# Bash script that configures the container to fit the above requirements:
# - nginx must be running as nginx user
# - nginx must be listening on all active IPs on port 8080
# - You cannot use apt-get remove

chown nginx:nginx /etc/nginx/nginx.conf
chmod 400 /etc/nginx/nginx.conf
sudo sed -i "s/80 default_server;/8080 default_server;" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
